#!/bin/sh

# MIT License
#
# Copyright (c) 2019-2020 Hyeonki Hong <hhk7734@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

RED=$(tput setaf 1)
# GREEN=$(tput setaf 2)
# ORANGE=$(tput setaf 3)
# BLUE=$(tput setaf 4)
# PURPLE=$(tput setaf 5)
# CYAN=$(tput setaf 6)
# LGRAY=$(tput setaf 7)

BOLD=$(tput bold)

DEFAULT=$(tput sgr0)

if [ "$(id -u)" -ne 0 ]; then
    printf "%sMust run as root privileges. %s%s\n" \
        "${RED}${BOLD}" \
        "Try 'sudo lot [options]'" \
        "${DEFAULT}" >&2
    exit 1
fi

# shellcheck source=lot
if ! [ -e '/usr/bin/lot' ]; then
    printf "%sFailed to find /usr/bin/lot.%s\n" \
        "${RED}${BOLD}" "${DEFAULT}" >&2
    exit 1
fi

calc_wt_size()
{
    # NOTE: it's tempting to redirect stderr to /dev/null, so supress error 
    # output from tput. However in this case, tput detects neither stdout or 
    # stderr is a tty and so only gives default 80, 24 values

    WT_HEIGHT=17
    WT_WIDTH=$(tput cols)

    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 80 ]; then
        WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 120 ]; then
        WT_WIDTH=120
    fi

    WT_MENU_HEIGHT=$((WT_HEIGHT-7))
}