#!/bin/sh

do_detect_board()
{
    [ "x${DEVICE}" = "x" ] &&
    [ -e "/proc/device-tree/model" ] &&
    DEVICE="$(cat /proc/device-tree/model)"

    case "$DEVICE" in
        "Hardkernel ODROID-N2")
            DEVICE=odroid-n2
            ;;
        *)
            DEVICE=Unknown
            ;;
    esac

    echo ${DEVICE}
}